// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexta.Infrastructure.DataBase;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexta.Infrastructure.DataBase.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.DetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NewPrice")
                        .HasColumnType("integer");

                    b.Property<int?>("OldPrice")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.DetailImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Base64String")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DetailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DetailId")
                        .IsUnique();

                    b.ToTable("DetailImages");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.NewsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.NewsImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Base64String")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NewsImages");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.OrderDetailEntity", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetailId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "DetailId");

                    b.HasIndex("DetailId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.UserDetailEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetailId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "DetailId");

                    b.HasIndex("DetailId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.DetailImageEntity", b =>
                {
                    b.HasOne("Nexta.Infrastructure.DataBase.Entities.DetailEntity", "Detail")
                        .WithOne("Image")
                        .HasForeignKey("Nexta.Infrastructure.DataBase.Entities.DetailImageEntity", "DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.NewsImageEntity", b =>
                {
                    b.HasOne("Nexta.Infrastructure.DataBase.Entities.NewsEntity", "News")
                        .WithOne("Image")
                        .HasForeignKey("Nexta.Infrastructure.DataBase.Entities.NewsImageEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.OrderDetailEntity", b =>
                {
                    b.HasOne("Nexta.Infrastructure.DataBase.Entities.DetailEntity", "Detail")
                        .WithMany("OrderDetails")
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexta.Infrastructure.DataBase.Entities.OrderEntity", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.OrderEntity", b =>
                {
                    b.HasOne("Nexta.Infrastructure.DataBase.Entities.UserEntity", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.UserDetailEntity", b =>
                {
                    b.HasOne("Nexta.Infrastructure.DataBase.Entities.DetailEntity", "Detail")
                        .WithMany("UserDetails")
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexta.Infrastructure.DataBase.Entities.UserEntity", "User")
                        .WithMany("UserDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.DetailEntity", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("OrderDetails");

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.NewsEntity", b =>
                {
                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Nexta.Infrastructure.DataBase.Entities.UserEntity", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
